const LeaderBoardDetail = [
	{
		contestTitle: 'BIT Code: September Round',
		date: 'October 1, 2020',
		listLink: '/',
		topContestants: [
			{
				name: 'Arshad Jamal',
				score: '400',
				branch: 'IT',
				batch: '2k18',
				codeChefId: 'doctorstrange8',
			},
			{
				name: 'Gaurav Kumar',
				score: '200',
				branch: 'CSE',
				batch: '2k17',
				codeChefId: 'gaurav_jfk',
			},
			{
				name: 'Sapan Ravidas',
				score: '200',
				branch: 'CSE',
				batch: '2k18',
				codeChefId: 'sapan1712',
			},
			{
				name: 'Utkarsh Raj',
				score: '100',
				branch: 'CSE',
				batch: '2k17',
				codeChefId: 'lorem_ipsum_73',
			},
			{
				name: 'Shivam Kedia',
				score: '100',
				branch: 'IT',
				batch: '2k19',
				codeChefId: 'skshivamkedia',
			},
		],
	},
	{
		contestTitle: 'BIT Code: October Round',
		date: 'October 30, 2020',
		listLink: '/',
		topContestants: [
			{
				name: 'Shyam Singh',
				score: '500',
				branch: 'CSE',
				batch: '2k18',
				codeChefId: 'd_evilal',
			},
			{
				name: 'Suveen Kumar',
				score: '500',
				branch: 'IT',
				batch: '2k16',
				codeChefId: 'usernotfound',
			},
			{
				name: 'Arshad Jamal',
				score: '500',
				branch: 'IT',
				batch: '2k18',
				codeChefId: 'doctorstrange8',
			},
			{
				name: 'Utkarsh Raj',
				score: '500',
				branch: 'CSE',
				batch: '2k17',
				codeChefId: 'lorem_ipsum_73',
			},
			{
				name: 'Piyush Gupta',
				score: '401',
				branch: 'CSE',
				batch: '2k19',
				codeChefId: 'guptapiyush233',
			},
		],
	},
	{
		contestTitle: 'BIT Code: March Round',
		date: 'March 23, 2021',
		listLink: '/',
		topContestants: [
			{
				name: 'Arshad Jamal',
				score: '4',
				branch: 'IT',
				batch: '2k18',
				codeChefId: 'doctorstrange8',
			},
			{
				name: 'Anurag Singh',
				score: '4',
				branch: 'IT',
				batch: '2k18',
				codeChefId: 'ryder7000',
			},
			{
				name: 'Rahul Kumar',
				score: '4',
				branch: 'CSE',
				batch: '2k18',
				codeChefId: 'pctablet505',
			},
			{
				name: 'Shivam Pandey',
				score: '3',
				branch: 'IT',
				batch: '2k19',
				codeChefId: 'shivampndey711',
			},
			{
				name: 'Anish Kumar Barnwal',
				score: '3',
				branch: 'IT',
				batch: '2k18',
				codeChefId: 'ak47forces',
			},
		],
	},
];

export default LeaderBoardDetail;
