const LeaderBoardDetail = [
	{
		contestTitle: 'BIT Code: November Round - 1',
		date: 'November 02, 2024',
		listLink: 'https://www.hackerrank.com/contests/bit-code-phase-1-round-1/leaderboard',
		topContestants: [
			{
				name: 'Aman Kumar Verma',
				score: '600',
				branch: 'IT',
				batch: '2k22',
				hackerrankId: 'amanverma0601201',
			},
			{
				name: 'Kumar Anshuman',
				score: '400',
				branch: 'ECE',
				batch: '2k22',
				hackerrankId: 'Kumar_Anshuman',
			},
			{
				name: 'Nikhil Ranjan',
				score: '300',
				branch: 'Electrical',
				batch: '2k23',
				hackerrankId: 'iamnikhilranjan',
			},
			{
				name: 'Ashish Kumar',
				score: '300',
				branch: 'IT',
				batch: '2k24',
				hackerrankId: 'ashishkumar_ab01',
			},
			{
				name: 'Pratham Kumar Sinha',
				score: '300',
				branch: 'ECE',
				batch: '2k22',
				hackerrankId: 'pratham_sinha',
			},
		],
	},
	{
		contestTitle: 'BIT Code: September Round',
		date: 'September 17, 2023',
		listLink: 'https://www.hackerrank.com/contests/bit-code-september/leaderboard',
		topContestants: [
			{
				name: 'Avinash Kumar',
				score: '600',
				branch: 'ECE',
				batch: '2k21',
				hackerrankId: 'avinash14808',
			},
			{
				name: 'Riya Gupta',
				score: '600',
				branch: 'Civil',
				batch: '2k22',
				hackerrankId: 'rhea36422',
			},
			{
				name: 'Harsh Singh',
				score: '600',
				branch: 'Chemical',
				batch: '2k20',
				hackerrankId: 'alex123qwas',
			},
			{
				name: 'Priti Bakshi',
				score: '600',
				branch: 'ECE',
				batch: '2k21',
				hackerrankId: 'pritibakshi33',
			},
			{
				name: 'Vishal kumar',
				score: '600',
				branch: 'CSE',
				batch: '2k22',
				hackerrankId: 'vishalkr22919811',
			},
		],
	},
	{
		contestTitle: 'BIT Code: August Round',
		date: 'August 23, 2023',
		listLink: 'https://www.hackerrank.com/contests/bit-code-august-1/leaderboard',
		topContestants: [
			{
				name: 'Tanish Kumar',
				score: '600',
				branch: 'EE',
				batch: '2k20',
				hackerrankId: 'tanish12395',
			},
			{
				name: 'Shubham Sourav',
				score: '600',
				branch: 'ECE',
				batch: '2k20',
				hackerrankId: 'shubhamjha2219',
			},
			{
				name: 'Priyanshu Malviya ',
				score: '600',
				branch: 'ECE',
				batch: '2k20',
				hackerrankId: 'priyanshumalviy1',
			},
			{
				name: 'Deepak Singh',
				score: '600',
				branch: 'ECE',
				batch: '2k21',
				hackerrankId: 'rebels1942',
			},
			{
				name: 'Anshu Kumar Mehta',
				score: '300',
				branch: 'IT',
				batch: '2k22',
				hackerrankId: 'krans_574',
			},
		],
	},
	{
		contestTitle: 'BIT Code: July Round',
		date: 'July 20, 2023',
		listLink: 'https://www.hackerrank.com/contests/bit-code-july/leaderboard',
		topContestants: [
			{
				name: 'Ashish Ranjan',
				score: '600',
				branch: 'Chemical',
				batch: '2k20',
				hackerrankId: 'pro_ashish_ranj1',
			},
			{
				name: 'Rahul Kumar',
				score: '600',
				branch: 'Production',
				batch: '2k22',
				hackerrankId: 'ApunichBhagwanHe',
			},
			{
				name: 'Kumar Anshuman',
				score: '300',
				branch: 'ECE',
				batch: '2k22',
				hackerrankId: 'Kumar_Anshuman',
			},
			{
				name: 'Ranjan Kumar Mahto',
				score: '300',
				branch: 'CSE',
				batch: '2k21',
				hackerrankId: 'ranjanmahto90',
			},
			{
				name: 'Rounak Kishan',
				score: '300',
				branch: 'CSE',
				batch: '2k22',
				hackerrankId: 'rk272627',
			},
		],
	},
];

export default LeaderBoardDetail;
