const LeaderBoardDetail = [
	{
		contestTitle: 'BIT Code: June Round',
		date: 'June 10, 2023',
		listLink: 'https://www.hackerrank.com/contests/hncc-bit-code-june/leaderboard',
		topContestants: [
			{
				name: 'Ashish',
				score: '1000',
				branch: '-',
				batch: '-',
				hackerrankId: 'pro_ashish_ranj1',
			},
			{
				name: 'Soham Mirikar',
				score: '600',
				branch: 'CSE',
				batch: '2k20',
				hackerrankId: 'sohammirikar',
			},
			{
				name: 'Tanweer Ansari',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: 'ansaritanweer836',
			},
			{
				name: 'Abhay Kumar',
				score: '600',
				branch: 'Chemical',
				batch: '2k22',
				hackerrankId: 'abhaykrofficial',
			},
			{
				name: 'Suryaprakash Pandey',
				score: '600',
				branch: 'CSE',
				batch: '-',
				hackerrankId: 'pandey_sp',
			},
		],
	},
	{
		contestTitle: 'BIT Code: February Round',
		date: 'February 25, 2020',
		listLink: 'https://www.hackerrank.com/contests/bit-code-feb/leaderboard',
		topContestants: [
			{
				name: 'Suprity Sinha',
				score: '1200',
				branch: 'CSE',
				batch: '2k20',
				hackerrankId: 'suprity12345',
			},
			{
				name: 'Arvindh Iyer',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: '2015arvindh',
			},
			{
				name: 'Krish Murarka',
				score: '600',
				branch: 'CSE',
				batch: '2k19',
				hackerrankId: 'murarka_krish',
			},
			{
				name: 'Ashish',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: 'pro_ashish_ranj1',
			},
			{
				name: 'Shubham Mishra',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: 'm_shubham0723',
			},
		],
	},
	{
		contestTitle: 'BIT Code: October Round',
		date: 'October 16, 2022',
		listLink: 'https://www.hackerrank.com/contests/bit-code-october/leaderboard',
		topContestants: [
			{
				name: 'Aman Kumar',
				score: '1000',
				branch: 'CSE',
				batch: '2k20',
				hackerrankId: 'Amank2854',
			},
			{
				name: 'Ashish',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: 'pro_ashish_ranj1',
			},
			{
				name: 'Shivam Bhagat',
				score: '600',
				branch: '-',
				batch: '-',
				hackerrankId: 'shivampkrr',
			},
			{
				name: 'Rakesh Reddy',
				score: '300',
				branch: 'IT',
				batch: '-',
				hackerrankId: 'rakeshreddy9541',
			},
			{
				name: 'Priyanshu Katyayni',
				score: '300',
				branch: 'ECE',
				batch: '2k21',
				hackerrankId: 'priyanshukatyay1',
			},
		],
	},
];

export default LeaderBoardDetail;
